- name: Get additional metrics endpoint port name
  ansible.builtin.set_fact:
    additional_metrics_port_name: "{{ endpoints.resources
      | selectattr('metadata.name', 'contains', item.name)
      | selectattr('metadata.name', 'contains', item.metrics_endpoint_name | default(item.name))
      | map(attribute='subsets') | first
      | map(attribute='ports') | first
      | selectattr('port', 'equalto', item.port)
      | map(attribute='name') | first }}"

- name: Declare ServiceMonitors
  kubernetes.core.k8s:
    template: servicemonitor.yml.j2
