---
- name: Create Grafana namespace
  kubernetes.core.k8s:
    name: "{{ dsc.grafana.namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Get Grafana client secret
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: "{{ dsc.keycloak.namespace }}"
    name: keycloak-client-secret-grafana-projects
  register: grafana_secret
  failed_when: grafana_secret.resources | length == 0

- name: Initialize grafana_name fact
  ansible.builtin.set_fact:
    grafana_name: "{{ dsc_name }}-prod"

- name: Set grafana_name
  when: dsc.global.environment != 'production'
  ansible.builtin.set_fact:
    grafana_name: "{{ dsc_name }}-horsprod"

- name: Deploy Grafana instance
  kubernetes.core.k8s:
    template: "{{ item }}"
  with_items:
    - grafana.yaml.j2
    - ingress.yaml.j2

- name: Get Grafana ClusterRoleBinding
  kubernetes.core.k8s_info:
    api_version: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    field_selectors:
      - metadata.name={{ dsc.grafana.namespace }}-view
  register: gf_crb

- name: Create Grafana ClusterRoleBinding
  when: gf_crb.resources | length == 0
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: "{{ dsc.grafana.namespace }}-view"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-monitoring-view
      subjects:
        - kind: ServiceAccount
          name: "{{ grafana_name }}-sa"
          namespace: "{{ dsc.grafana.namespace }}"
