- name: Get tasks
  ansible.builtin.uri:
    validate_certs: "{{ dsc.exposedCA.type == 'none' }}"
    force_basic_auth: true
    url: https://{{ nexus_domain }}/service/rest/v1/tasks
    method: GET
    user: admin
    password: "{{ nexus_admin_password }}"
  register: nexus_tasks

- name: Set Clean_Docker_unused_stuff_task fact
  ansible.builtin.set_fact:
    Clean_Docker_unused_stuff_task: "{{ nexus_tasks.json['items']
      | selectattr('name', 'equalto', 'Clean Docker unused stuff')
      | map(attribute='name') | first | default('missing') }}"

- name: Set Clean_Docker_uploads_task fact
  ansible.builtin.set_fact:
    Clean_Docker_uploads_task: "{{ nexus_tasks.json['items']
      | selectattr('name', 'equalto', 'Clean Docker uploads')
      | map(attribute='name') | first | default('missing') }}"

- name: Set Compact_DSO_Blob_Store_task fact
  ansible.builtin.set_fact:
    Compact_DSO_Blob_Store_task: "{{ nexus_tasks.json['items']
      | selectattr('name', 'equalto', 'Compact DSO Blob Store')
      | map(attribute='name') | first | default('missing') }}"

- name: Initialize nexus_tasks_check fact
  ansible.builtin.set_fact:
    nexus_tasks_check: ""

- name: Set nexus_tasks_check fact
  when: (Clean_Docker_unused_stuff_task == 'missing')
    or (Clean_Docker_uploads_task == 'missing')
    or (Compact_DSO_Blob_Store_task == 'missing')
  ansible.builtin.set_fact:
    nexus_tasks_check: "missing"
